# Generated by Django 3.1.3 on 2020-11-09 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Book's natural language", max_length=50)),
                ('code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('pub_date', models.DateField()),
                ('isbn', models.CharField(help_text='13 Character - numbers only', max_length=13, verbose_name='ISBN')),
                ('pages_num', models.PositiveIntegerField(help_text='Number of pages')),
                ('cover', models.ImageField(default='covers/default.jpg', upload_to='covers/')),
                ('authors', models.ManyToManyField(to='catalog.Author')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.language')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
