# Generated by Django 3.1.3 on 2020-11-28 18:25

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Book title', max_length=150)),
                ('pub_date', models.DateField(blank=True, help_text='Publication date', null=True, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)])),
                ('isbn', models.CharField(blank=True, help_text='ISBN-13 (unmbers only)', max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='\\d{13}')], verbose_name='ISBN')),
                ('pages_num', models.PositiveIntegerField(blank=True, default=1, help_text='Number of pages', null=True, validators=[django.core.validators.MaxValueValidator(9999)])),
                ('cover', models.ImageField(default='default.jpg', help_text='Photo cover', upload_to='covers/')),
                ('slug', models.SlugField(max_length=300)),
                ('authors', models.ManyToManyField(help_text='Author(s)', to='catalog.Author')),
                ('language', models.ForeignKey(blank=True, help_text='Natural language', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
