# Generated by Django 3.1.3 on 2020-12-06 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ('name',)},
        ),
    ]
