# Generated by Django 3.1.3 on 2020-11-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20201111_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(help_text='Author(s)', to='catalog.Author'),
        ),
    ]
