# Generated by Django 3.1.3 on 2020-11-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20201115_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='default.jpg', help_text='Photo cover', upload_to='covers/'),
        ),
    ]
